### ISSUE TITLE
Cannot get continuous data from PC80B-BLE

### ISSUE THREAD

**Issue by thewyrdguy** [viatom-develop/LepuDemo#3]
I am trying to obtain realtime ECG data from PC80B-BLE

When using internal lead (fast mode), I am receiving expected sequence:
```
Connected; Firmware: 1.2.0, Model: M80861, Manufacturer: Made by Compx
All controls are in place, ctl value 001800180000004800
EventPc80bTime(0x33:0f0e160f08e80705 )
EventPc80bFastData(0xdd:0000200000810008 seqNo=0, hr=0, gain=2, channel=0, mmode=detecting, mstage=detecting, leadoff=True, datatype=1, ecgFloats=25)
...
EventPc80bFastData(0xdd:3f0020510001fe07 seqNo=63, hr=0, gain=2, channel=1, mmode=fast, mstage=preparing, leadoff=False, datatype=1, ecgFloats=25)
...
EventPc80bFastData(0xdd:800040520001ea07 seqNo=128, hr=0, gain=4, channel=1, mmode=fast, mstage=measuring, leadoff=False, datatype=1, ecgFloats=25)
...
EventPc80bFastData(0xdd:0e0040530000 seqNo=14, hr=0, gain=4, channel=1, mmode=fast, mstage=analyzing, leadoff=False, datatype=0, ecgFloats=0)
EventPc80bFastData(0xdd:0e00405400022024 seqNo=14, hr=0, gain=4, channel=1, mmode=fast, mstage=result, leadoff=False, datatype=2, ecgFloats=0)
EventPc80bFastData(0xdd:0e0040550000 seqNo=14, hr=0, gain=4, channel=1, mmode=fast, mstage=stop, leadoff=False, datatype=0, ecgFloats=0)
EventPc80bTime(0x33:030f160f08e80705 )
EventPc80bTime(0x33:060f160f08e80705 )
```
(and then 0x66 if I press "Send").

But when using external lead, sequence begins as expected:
```
EventPc80bTime(0x33:1c0c160f08e80705 )
EventPc80bFastData(0xdd:0000200000810008 seqNo=0, hr=0, gain=2, channel=0, mmode=detecting, mstage=detecting, leadoff=True, datatype=1, ecgFloats=25)
...
EventPc80bFastData(0xdd:3c0020a50000 seqNo=60, hr=0, gain=2, channel=2, mmode=continuous, mstage=stop, leadoff=False, datatype=0, ecgFloats=0)
```
but after that no continuous records are arriving. Instead, I receive a frame 0x55 (I do not know what it is) every second, with unchanging payload, interspersed with 0x33 (time?) frame every three seconds. If I stop acquisition, I receive 0xAA as expected:
```
EventPc80bTime(0x33:2b0c160f08e80705 )
EventPc80b???(0x55:800032ffdc054d4d323007622543 )
EventPc80b???(0x55:800032ffdc054d4d323007622543 )
EventPc80b???(0x55:800032ffdc054d4d323007622543 )
EventPc80bTime(0x33:2e0c160f08e80705 )
EventPc80bOff(0xaa:00 )
EventPc80bOff(0xaa:00 )
EventPc80bTime(0x33:310c160f08e80705 )
```
**Official viatom Android app behaves the same way: it stops showing the curve when the unit finishes "preparing".**

Is this a problem in the unit's firmware? If so, does the fix exist?

Or do I need to write some command frames to the device to enable acquisition of continuous data?

Thank you.

(I understand that this is not the correct place to ask, but I cannot find any better contact point...)

**Comment by Chenyongfeng-424** [comment]
You need to respond when receiving 0x55.
You can contact our sales team for more detailed assistance.

**Comment by thewyrdguy** [comment]
Thanks a lot @Chenyongfeng-424 for the help!

I don't know who your sales team are, or how to contact them, but I am now able to get continuous data frames!
